### ISSUE TITLE
The workers render with blender internal instead of cycles

### ISSUE THREAD

**Issue by zuggamasta** [armadillica/flamenco#213] opened 2017-12-05 15:25 UTC
Hi there,

My setup is:
Macbook with blender 2.79 and cloud-addon
Windows Machine running flamenco magager and worker

I was able to send jobs with flamenco but I got error messages and then I saw that I was only rendering the blender internal version of my scene. (took me a while to figure that out actually)

[WorkerDUMP.txt](https://github.com/armadillica/flamenco/files/1531678/WorkerDUMP.txt)
[ManagerDUMP.txt](https://github.com/armadillica/flamenco/files/1531680/ManagerDUMP.txt)

cheers
Alex

**Comment by sybrenstuvel** [comment] 2017-12-05 16:03
What happens if you run `'C:/Users/Alexander/Dropbox/Flamenco/Windows/blender.exe C:/Users/Alexander/Dropbox/Flamenco/render/storage/2017-12-05-003059.424438-zuggamasta-awesome8.flamenco/awesome8.flamenco.blend` on your worker?

Also, are you 100% sure that the files were synced with Dropbox before job execution started?

**Comment by zuggamasta** [comment] 2017-12-05 16:07
Hi Sybren,
thank you for your quick notice.

Dropbox: I'm syncing files over local network 300kb should be quite fast anyway.

I will try to render files by hand/commandline tonight. And also pointing to a blender build that is not on dropbox to minimize any other operations that could happen on the dropbox side of things.

Cycles was the active render engine on all occasions.
cc: @fsiddi

**Comment by zuggamasta** [comment] 2017-12-05 21:45
Hi @sybrenstuvel I tried running  `C:/Users/Alexander/Dropbox/Flamenco/Windows/blender.exe C:/Users/Alexander/Dropbox/Flamenco/render/storage/2017-12-05-003059.424438-zuggamasta-awesome8.flamenco/awesome8.flamenco.blend ` which did not really work and showed that addons and modules could not be loaded. I now set up a new location for the executable, pointing to my regular blender build.

But from here I'm not able to setup the manager correctly, after installing I get:
```
[36mINFO[0m[2017-12-05T22:38:00+01:00] Getting tasks from upstream Flamenco https://cloud.blender.org/api/flamenco/managers/5a22916e8ac31b1616aef0a7/depsgraph
[33mWARN[0m[2017-12-05T22:38:00+01:00] SendTaskUpdates: Error 400 POSTing to https://cloud.blender.org/api/flamenco/managers/5a22916e8ac31b1616aef0a7/task-update-batch
    body:
{"_status": "ERR", "_error": {"code": 400, "message": "no JSON payload received"}}
[33mWARN[0m[2017-12-05T22:38:00+01:00] TaskUpdatePusher: unable to push to upstream Flamenco Server: SendTaskUpdates: Error 400 POSTing to https://cloud.blender.org/api/flamenco/managers/5a22916e8ac31b1616aef0a7/task-update-batch
[36mINFO[0m[2017-12-05T22:38:00+01:00] SendStartupNotification: trying to send notification.
[36mINFO[0m[2017-12-05T22:38:00+01:00] Timer 'StartupNotifier' goroutine shutting down.
[36mINFO[0m[2017-12-05T22:38:00+01:00] SendStartupNotification: Done sending notification to upstream Flamenco
[33mWARN[0m[2017-12-05T22:38:01+01:00] SendTaskUpdates: Error 400 POSTing to https://cloud.blender.org/api/flamenco/managers/5a22916e8ac31b1616aef0a7/task-update-batch
    body:
{"_status": "ERR", "_error": {"code": 400, "message": "no JSON payload received"}}
[33mWARN[0m[2017-12-05T22:38:01+01:00] TaskUpdatePusher: unable to push to upstream Flamenco Server: SendTaskUpdates: Error 400 POSTing to https://cloud.blender.org/api/flamenco/managers/5a22916e8ac31b1616aef0a7/task-update-batch
[36mINFO[0m[2017-12-05T22:38:01+01:00] ImageWatcherHTTPPush: Channel started at /imagewatch for 192.168.178.69:53848
[33mWARN[0m[2017-12-05T22:38:02+01:00] SendTaskUpdates: Error 400 POSTing to https://cloud.blender.org/api/flamenco/managers/5a22916e8ac31b1616aef0a7/task-update-batch
    body:
```

**Comment by sybrenstuvel** [comment] 2017-12-06 09:58
Hint: this will make the output easier to copy-paste: `flamenco-manager --whatever --you --use 2>&1 | cat`

Can you also add the `--debug` option so that we get more details, and tell me which version of Flamenco Manager you're using?

**Comment by sybrenstuvel** [comment] 2017-12-06 14:05
Never mind, was my mistake caused by ae4d2a8676f8658942e3fa7ebd59aacb64ddab43, is now fixed.

**Closed by sybrenstuvel** 2017-12-06 14:05 UTC

**Comment by zuggamasta** [comment] 2017-12-06 15:49
Hello @sybrenstuvel sorry to bother you once again on the issue but when will a new build be available as I am curretntly not setup to build the manager myself?

Thank you for your quick help.

**Comment by sybrenstuvel** [comment] 2017-12-06 16:09
It was a server side thing, you don't have to do anything 😀
