### ISSUE TITLE
dashboard cannot save and read settings

### ISSUE THREAD

**Issue by antonvdh** [armadillica/flamenco#136] opened 2015-05-23 06:56 UTC
After two months the 2.0.0.-beta.1 released it is still not usable. 
So I Installed today the latest flamenco zip files, saved settings but they are still not read by dashboard web interface. 
Also installed Flamenco Blender plugin when trying save and send there is a report error : 
Error running BAM is it installed?   

I would like to run the beta Flamenco renderfarm version.
Can you please tell me where to look for the problem.

**Comment by fsiddi** [comment] 2015-06-10 23:31
Duplicate of #59. We will address this as soon as possible. We started with commit c4ca982, which lays the foundation to make a good interface to interact with the manager via the dashboard.

Regarding the BAM error, try to `pip3 install blender-bam` in your terminal. If you are still having problems, please open a separate issue :)

**Closed by fsiddi** 2015-06-10 23:31 UTC

**Comment by antonvdh** [comment] 2015-06-11 20:08
Thanks
Op 11 jun. 2015 01:32 schreef "Francesco Siddi" <notifications@github.com>:
