### ISSUE TITLE
Subprocess from flamenco-worker-subprocess.pid is still running

### ISSUE THREAD

**Issue by ozitvogel** [armadillica/flamenco#243] opened 2020-03-22 08:41 UTC
We have 1 manager and 3 workers on 3 linux machines. One machine running manager+worker, the others running only one worker each.
Most of our renders enter some kind of SOFT-FAIL loops to endup finaly in FAILED.
Most of the time the error is related to blender processes already existing :
`03-21T04:18:41.004794+00:00: blender_render.(task_id=5e74ee44eda2605ab6bdbf8f, command_idx=0): Error in settings: Subprocess from flamenco-worker-subprocess.pid is still running: psutil.Process(pid=26412, name='blender', started='05:17:45')`

The manager as well as the cloud tend to report false positives as sometimes same task ids are assigned to multiple workers and it seems that it fails because they pingpong each other.

Any idea here ?

**Comment by sybrenstuvel** [comment] 2020-03-23 12:35
This is very strange. Are you 100% sure the workers are all registered with the Manager as separate workers? They each should have their own `worker_id` and `worker_secret` in their local configuration file.

When a worker fails so often it gets blacklisted from that task type on that particular job, the tasks it failed before are re-queued to allow another worker to execute them. This is to prevent issues on a single machine from failing all tasks it touches. In such a case it's normal to see a task being handed to multiple workers.

**Comment by ozitvogel** [comment] 2020-03-24 07:24
Hello, I don't see `worker_id` or `worker_secret` fields in the`flamenco-worker.cfg` file.

Shall I add them and put arbitrary unique values ? Please note that the manager web ui shows different `worker_id` and have different names (I presume this is the `worker_id`).

Also, I noticed that some tasks had been set to render images in the same output dir with the same file name. Maybe that's the reason of my issue ?

**Comment by ozitvogel** [comment] 2020-03-25 10:38
OK, those 2 fields are auto-generated into ~.flamenco-worker.cfg. Both fields are different accross the workers. Same behaviour still continues to happen after some hours

**Comment by OSSC313** [comment] 2021-03-04 09:10
Hello!
Did You manage to resolve the problem? 
I have exactly the same issue : **blender_render.(task_id=60409f7f0d827f2cfc2e8ccb, command_idx=0): Invalid settings: Subprocess from flamenco-worker-subprocess.pid is still running: psutil.Process(pid=7416, name='svchost.exe', started='2021-02-13 19:16:46')**
We have 11 workers on Windows10 - Only one of them has this problem

**Comment by sybrenstuvel** [comment] 2021-12-17 10:39
This situation should be improved in Flamenco Worker v2.6 (current is v2.7). It's still a bit of a mystery to me what the root cause is, but at least the new way it handles these "subprocess is still running" situations should be better.

Instead of keeping the process running, the Worker will now simply shut down when it detects this; this should take down its child processes as well. It then depends on the environment it's started from to restart it again -- this is the default behaviour when running on Linux via systemd. I'm too unfamiliar with running services on Windows to advice how to set the same auto-restarting behaviour there.

**Comment by sybrenstuvel** [comment] 2021-12-17 10:40
I'm closing this task as I think it should be sufficiently resolved (it shouldn't block any production). If the issue is still causing problems, don't keep it to yourself ;-)

**Closed by sybrenstuvel** 2021-12-17 10:40 UTC
