### ISSUE TITLE
After install Flamenco 2.0.0-beta.1 settings has been saved into sqlite base, but they are not read by dashboard web interface

### ISSUE THREAD

**Issue by nntc** [armadillica/flamenco#127] opened 2015-04-14 19:49 UTC
Use the same instructions for installing versions 2.0.0-alpha and 2.0.0-beta.1. Version 2.0.0-alpha working, in version 2.0.0-beta.1 the problem:
After install Flamenco 2.0.0-beta.1 settings has been saved into sqlite base, but they are not read by dashboard web interface. In debug silence.

I would like to still run a version 2.0.0-beta.1, but faced with a problem. Please tell me where to look for the problem.

Thank.

P.S.: Render Farm Version 2.0.0-alpha is working fine. I hope that will help me to run the latest version

**Comment by Eibriel** [comment] 2015-04-15 23:17
Sadly the User interface to expose that settings is not implemented, let me know if you have some problem with that and I'll assist you.

**Comment by fsiddi** [comment] 2015-06-10 23:28
Duplicate of #59. We will address this as soon as possible. We started with commit c4ca98226558ee8cfe5caa5118b1228e0983ba1a, which lays the foundation to make a good interface to interact with the manager via the dashboard.

**Closed by fsiddi** 2015-06-10 23:28 UTC
